### PR TITLE
Add fileRemoved event.

### PR DESCRIPTION
**Pull request by SuberFu**
Add fileRemoved event for when a file is removed from the upload queue.

Also updated the readme for fileSubmitted for more elaboration on when it's called (namely, after the file is added to the upload queue).

### CODE REVIEW

**Comment by SuberFu** [comment]
Added a fileRemoved event. The goals are as followed.
1. API symmetry: There's an event for when files are added to upload queue, but no equivalent event for when a file is removed from upload queue (off-side, perhaps a "fileRemoving" to allow user to cancel a file removal? Although that's a case I can't think of any use for).
2. Potentially cleaner user code: Users of flow.js may have several external states that depends on the upload-queue of flow.js. Instead of having a wrapper code that specifically target all cases where a file could be removed (for example, invoking cancel() on individual FlowFile, invoking cancel() on the Flow object, adding new files in singleFile mode), an event allow user to catch all instance of when a file leaves the upload queue.

**Comment by commandtab** [comment]
This is great! This will simplify my wrapping of Flow.js in a React component. :+1:

**Comment by evilaliv3** [comment]
@commandtab have you already tested the patch? could you provide your feedback?

**Comment by commandtab** [comment]
I just applied and tested the patch, and it triggered the `fileRemoved` event as described.

**Comment by evilaliv3** [comment]
@SuberFu would you please also implement the proper unit test for it?

**Comment by SuberFu** [comment]
Trying to run "grunt karma:watch", but it keeps trying to connect to SauceLab, is it supposed to do that?

**Comment by evilaliv3** [comment]
okay!

**Comment by SuberFu** [comment]
Just added the unit tests here #166

**Pull request merged**
