### PR TITLE
Reenable SauceLabs CI in v3

### PR DESCRIPTION
**Pull request by drzraf**
https://github.com/flowjs/flow.js/issues/322

### CODE REVIEW

**Comment by drzraf** [comment]
@evilaliv3  / @AidasK
- karma is running (good
- The code is not being tested on SauceLabs but using a local Firefox 63 instance (from within Travis-CI?)

**Comment by drzraf** [comment]
Second attempt:
The problem is that SauceLabs apparently does not accept some browser versions (https://travis-ci.org/github/flowjs/flow.js/jobs/753197936#L265)

**Comment by evilaliv3** [comment]
@drzaf as for the SAUCE_ACCESS_KEY i can manage to load it on travis or to load it encrypted; Lets finish the patch and i will then take care of this.

As for the issues on the browser versions i suspect that we may be using an outdated version of the webdriver; i'm checking on this right know

Typically when choosing version i like to have the first version on which we offer compatibility (based on the capabilities we use and checking it on caniuse) and then have the latest available stableversion of each browser identified on saucelabs by the keyword stable so that it automatically keep updating)

**Comment by evilaliv3** [comment]
@drzraf looking at https://github.com/karma-runner/karma-sauce-launcher#readme i read that in relation to W3C mode you should check the following resource and update the configruation for the browsers

```    // For W3C way of setting the capabilities check
    // https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/
    // And select WebDriver (W3C) Selenium 3/4, Webdriver.io```

Please let me know if you need any support on this.

**Comment by evilaliv3** [comment]
Key added to travis @drzraf @AidasK 

Screenshot_2021-01-07 flowjs flow js - Travis CI

**Comment by drzraf** [comment]
https://wiki.saucelabs.com/display/DOCS/W3C+Capabilities+Support

Brower | W3C version
-- | --
Chrome | 75 and above
Edge | All
Firefox | 55 and above
Internet Explorer | All
Safari | 12 and above

Are we ok upgrading testsuite to these versions?
Isn't there a way to keep testing older versions on SauceLabs?

**Comment by drzraf** [comment]
@evilaliv3  : In case you see what's wrong with that karma's Sauce configuration.

**Review by AidasK — APPROVED** [review]

**Comment by drzraf** [comment]
I'm still struggling to get SauceLabs to work.
@evilaliv3 : Would you mind giving me an access to SauceLabs? I could then check whether my local tunnels actually go well and attempt to run SauceLabs from localhost. (I actually can do it but lack some information from SauceLabs backend)

**Comment by drzraf** [comment]
Dears, it was painful (unsupported versions, saucelabs errors, saucelabs timeout, options object passing format, ...) it finally got it passed but... only with tested on "new" browsers.

I suggest to merge the PR as-is but enable *more* Saucelabs browsers version in a subsequent PR.
I couldn't remove Saucelabs username/keys because it seems Travis is not passing those registered in its configuration (@evilaliv3)

It was sufficiently painful that I still consider TestingBot (#325) a very compelling option.

**Comment by AidasK** [comment]
@drzraf It does not matter what you choose, just make sure it's working. Don't waste time on Saucelabs if it's so troublesome. Automatic tests on couple of browsers is good for me too

**Comment by evilaliv3** [comment]
@drzraf : i'm sorry i just noticed your message. 

I tried to access the accont on saucelabs but it seems that it is not connected to my email address anymore.

@AidasK : maybe i already passed it to you? did you received any email ?

**Comment by AidasK** [comment]
@evilaliv3 No, I can't see any project on Saucelabs

**Pull request merged**
