### PR TITLE
Testing bot

### PR DESCRIPTION
**Pull request by drzraf**
#322

### CODE REVIEW

**Comment by AidasK** [comment]
Looking great, you can merge it. Though you still need env var added somethere in travis?

**Comment by drzraf** [comment]
Where do we set Travis variable / Should I do the following on my account?
Screenshot from 2021-01-06 11-53-17

**Comment by AidasK** [comment]
Please do, approve it :). I have personaly tried it too, but travis can not find flow.js repository even though I am the owner 

image
image

**Comment by drzraf** [comment]
Closing this one since SauceLabs seems to still work so far (but note that I still have no access to that account myself).
We may still later refer to the `karma.conf.js` changes if we were to need them.

**Pull request closed without merging**
