### PR TITLE
Allow reupload of same file once the upload is complete

### PR DESCRIPTION
**Pull request by Karankang007**
Adding an option to override the default behavior of ignore reupload of the same file.

### CODE REVIEW

**Comment by AidasK** [comment]
Tests ar not passing because you are using `opts` instead of `this.opts`, please fix  and it will be merged. Thanks

**Comment by AidasK** [comment]
Could you add documentation for this option to the readme?

**Comment by Karankang007** [comment]
Added documentation for this option.
https://github.com/flowjs/flow.js/pull/113

**Comment by lucretiu** [comment]
Could you please add this merge into the version in the dist directory? Installing Flow using bower ignores the src directory, which actually contains the Flow version that allows this behaviour. I spent an hour or so trying to find why duplicate downloads were not accepted, only to find out that the version I have installed, even though it's "the latest" one, is not the latest one :(
It's even more confusing because the README which is shown on github says that the option is available.

**Comment by AidasK** [comment]
Sorry for this confusion, I will try to release this as soon as possible.

**Comment by soccerloway** [comment]
Hi, I need using this option in my project, but I found this option didn't merge into the version in the dist directory. So I tried to use the version in the  src directory. Bad luck, it throw an error said ' domNode.appendChild is not a function '. I also use ng-flow.js in my project.
Help me, thx~!

**Pull request merged**
