### PR TITLE
Move bytes field from FlowFile to FlowChunk

### PR DESCRIPTION
**Pull request by princejwesley**
`bytes` field is in wrong place. This PR fixes it.

### CODE REVIEW

**Comment by drzraf** [comment]
There is clearly a problem. `bytes` is defined in FlowFile while it should be in FlowChunk.
Another problems is the name. It's actually used by `prepareXhrRequest` as a `blob` parameter.
`blob`, `payload`, `content` all seem better wording for what this variable is for (the comment-doc could also clarify this).
@princejwesley : Are you willing to reroll the patch in such a way?

**Comment by AidasK** [comment]
This is a bug! I think we can merge it since `prepareXhrRequest` was not touched by this mr

**Comment by drzraf** [comment]
Sure, but it won't merge against neither master nor v3. What do you think about renaming the variable ?

**Comment by AidasK** [comment]
we can rename it in v3 branch and this fix should be made in a different commit. We can't rename it on master because it would be a BC

**Comment by AidasK** [comment]
https://github.com/flowjs/flow.js/pull/328

**Pull request closed without merging**
