### PR TITLE
Implement cross-compatibility testing by means of SauceLabs

### PR DESCRIPTION
**Pull request by evilaliv3**
@AidasK: i just implemented the browser testing by implementing the following:
1. removing of wrong packages in packages.json
2. updating of version of the packages outdated
3. updating karma configurations by cleaning them a little
4. added tests for each of the targeted browser by adding the first version compatible/available and the latest version available.

looking at https://travis-ci.org/evilaliv3/flow.js/builds/93243137 you can see that test are running but currently failing on all browser; it would be great if starting from this output you could fix what is failing and we start iterating together in improving the library!

### CODE REVIEW

**Comment by AidasK** [comment]
Strange, tests should be working at least for chrome browser. Maybe updated packages caused this issue? 
It would be great if you could make this work. Currently I don't have much time, but if you have any questions, please ask. I would really like to have this done.

**Comment by evilaliv3** [comment]
done! just waiting for the tests to complete and then i will merge it :)

The issue was in the fact that you built FakeXMLHttpRequestUpload.js atop of sinon-1.7.3.js and i tried to update also sinon to 1.17.2.

**Comment by evilaliv3** [comment]
@AidasK i'm ready to integrate but i'm missing the write access to the repository! :)

can you please add me to this, fusty-flow.js and ng-flow so that i can properly help you on these projects?

**Comment by AidasK** [comment]
Sorry, I though I have already added you. Github team management is a bit messed up. Try pushing it now

**Pull request merged**
