### PR TITLE
Add functionality to change Raw Body Data before sending.

### PR DESCRIPTION
**Pull request by aayusharyan**
Add functionality to change Raw Body Data before sending.
This is particularly helpful when using Upload with Google Storage and many other platforms where we have to upload multipart related form data. (i.e. Different parts in the same request).
Example:
Google Cloud Storage expects data body to be in this format.
[BOUNDARY] is the Content Boundary which can be set using Custom Header function.
[FILE_DATA] is actually the chunk body in this case. (which is a blob).
```
--[BOUNDARY]
Content-Type: application/json; charset=UTF-8

{
  "name": "myObject",
  "metadata": {
  "a":"b"
  }
}

--[BOUNDARY]
Content-Type: image/jpeg

[FILE_DATA]
--[BOUNDARY]--
```

If this is feasible and merged, then I'll change the Documentation...

### CODE REVIEW

**Comment by aayusharyan** [comment]
This PR will fix. https://github.com/flowjs/flow.js/issues/170

**Comment by AidasK** [comment]
I think I can merge this, though it would be great that you could include GCS usage example with this option too and add this param in the docs

**Comment by aayusharyan** [comment]
@AidasK 
Hey,
Thanks for the quick response.
It can be used to customize like this. 👇 
```
var preprocessChunk = function(flowChunk, data) {
  var e = data.get('file');
  var chunk_data = flowChunk.bytes;
  var chunkNumber = flowChunk.offset;

  var objectNameInfo = {
    'name': 'file'+chunkNumber+'_.jpg',
    'metadata': {
        'chunkNumber': chunkNumber
    }
  };
  var jsonse = JSON.stringify(objectNameInfo);

  var fileMetaBlob = new Blob([jsonse], {type: 'application/json'});

  var blob = new Blob([
    "--foo_bar_baz\n",
    "Content-Type: "+fileMetaBlob.type+"; charset=UTF-8\n",
    "\n",
    fileMetaBlob,
    "\n",
    "--foo_bar_baz\n",
    "Content-Type: "+chunk_data.type+"\n",
    "\n",
    chunk_data,
    "\n",
    "--foo_bar_baz--",
  ], {type: "text/plain"});
  
  return blob;
}
```

However, I am not sure what to include in the [documentation](https://github.com/flowjs/flow.js/blob/master/README.md). I mean, there is no example for other functionalities of the library. So, maybe keep it uniform and include explanation only without example... 🤷‍♂

**Comment by AidasK** [comment]
Add param and explanation to the docs and link to this issue #276

**Comment by aayusharyan** [comment]
@AidasK 
Please check now.

**Comment by AidasK** [comment]
Thanks for your time, merged

**Pull request merged**
