### PR TITLE
Stop retrying chunks when file paused

### PR DESCRIPTION
**Pull request by JonUK**
This is a fix for an issue I hit where a chunk failed to upload (as device was offline) and then the file was paused. Even though the file was now paused, the chunk uploading was still retried (while device still offline) and once the `maxChunkRetries` limit hit, the file upload was considered failed, all still while the file was paused.

### CODE REVIEW

**Comment by JonUK** [comment]
I've bumped the patch version via the `grunt release` step but if this is not desired, can always re-raise without the version number change.

**Comment by AidasK** [comment]
Yes, you should not change the dist files. Does the tests pass?

**Comment by JonUK** [comment]
Yes... the unit tests all passed. I will revert the `dist` and version number changes.

**Comment by JonUK** [comment]
Done

**Comment by AidasK** [comment]
Thanks!

**Comment by JonUK** [comment]
Hi. Will this `v2.14.1` be published to npm?

**Comment by AidasK** [comment]
Published!

**Comment by JonUK** [comment]
Much appreciated

**Pull request merged**
